# Generated by Django 5.0.2 on 2024-02-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieData',
        ),
    ]
